server:
  port: 6692

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO


spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          messaging-client-oidc2:
            provider: spring
            client-id: messaging-client2
            client-secret: secret2
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:6692/login/oauth2/code/{registrationId}"
            scope: openid, profile, message.read
            client-name: messaging-client-oidc2
        provider:
          spring:
            issuer-uri: http://localhost:6680
messages:
  base-uri: http://127.0.0.1:6690/messages